name: 'Telegram Alert'

on: 
  push:
    branches:
    - main
  workflow_dispatch:
  

jobs:
  alert:
    name: 'Alert Groups'
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Stat Calculate
         id: changes
         run: |
           git diff-tree --no-commit-id --name-status -r ${{ github.sha }} > changes.txt 
           git diff --stat ${{ github.sha }} > stats.txt

       - name: Format Telegram message on push
         id: format_message
         run: |
            FILE_CHANGES=$(cat changes.txt)
            STATS=$(cat stats.txt)
            GIT_USER=$(git log -1 --pretty=format:'%an')
            COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
            MESSAGE="New Changes on super-patch action..\n\n\nFiles changed:\n$FILE_CHANGES\n$STATS\n\nAuthored by: @${GIT_USER}\nCheck changes with [main](${COMMIT_URL})"
            echo "::set-output name=message::$MESSAGE"

       - name: Send Telegram message on push
         uses: appleboy/telegram-action@master
         with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.format_message.outputs.message }}


          
  workflow_dispatch_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find YAML file triggered
        id: find-yml
        run: |
          YAML_FILE=$(find .github/workflows/ -name "*.yml" -print -quit)
          echo "yaml_file=$YAML_FILE" >> $GITHUB_ENV

      - name: Format Telegram message on workflow dispatch
        id: format_message
        run: |
          GIT_USER=$(git log -1 --pretty=format:'%an')
          WORKFLOW_NUM=${{ github.run_id }}
          YAML_FILE=${{ env.yaml_file }}
          MESSAGE="@${GIT_USER} is triggering a ${WORKFLOW_NUM} workflow using ${YAML_FILE}"
          echo "::set-output name=message::$MESSAGE"

      - name: Send Telegram message on workflow dispatch
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.format_message.outputs.message }}

  workflow_complete:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on workflow completion
        if: always()
        run: |
          TAG=$(git describe --tags)
          WORKFLOW_NUM=${{ github.run_id }}
          MESSAGE="The workflow ${WORKFLOW_NUM} has been completed with the following:\n\nTag: ${TAG}\nResults:\nPublished a GitHub release and created an artifact"
          echo "::set-output name=message::$MESSAGE"

      - name: Send Telegram message on workflow completion
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.notify.outputs.message }}

