name: Purge Wipe Releases (if you want a breather)

on:
    workflow_dispatch:
jobs: 
    test:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
                - uses: actions/checkout@v3
                - uses: Nats-ji/delete-old-releases@v1
                  with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    keep-old-minor-releases: false
                    remove-tags: true
                - name: wipe all tags because they are annoying asf
                  uses: dev-drprasad/delete-tag-and-release@v1.1
                  with: 
                    tag_name: '*'
                    github_token: ${{ secrets.GITHUB_TOKEN }}